const products = [
    {
        id: 1,
        name: 'Perapad',
        brand: 'Pera',
        image: 'imagenes/pearpad.jpg',
        description: 'Ideal para la portabilidad',
        price: 150,
        stock: 4,
    },
    {
        id: 2,
        name: 'Peraphone',
        brand: 'Pera',
        image: 'imagenes/peraphone.webp',
        description: 'Pera reinventa el celular',
        price: 180,
        stock: 10,
    },
    {
        id: 3,
        name: 'Perawatch',
        brand: 'Pera',
        image: 'imagenes/perawatch.png',
        description: 'El mejor smart watch es de Pera.',
        price: 90,
        stock: 4,
    },
    {
        id: 4,
        name: 'Macpera',
        brand: 'Pera',
        image: 'imagenes/peramac.webp',
        description: 'El PC portátil más veloz.',
        price: 500,
        stock: 7,
    },
    {
        id: 5,
        name: 'Macpera mini',
        brand: 'Pera',
        image: 'imagenes/peramini.png',
        description: 'Velocidad mini',
        price: 140,
        stock: 4,
    },
    {
        id: 6,
        name: 'Perapad mini',
        brand: 'Pera',
        image: 'imagenes/perapadmini.webp',
        description: 'Perapad en la palma de tu mano.',
        price: 100,
        stock: 2,
    },
    {
        id: 7,
        name: 'Perapad pro',
        brand: 'Pro',
        image: 'imagenes/perapadpro.png',
        description: 'Perapad con más potencia.',
        price: 290,
        stock: 7,
    },
    {
        id: 8,
        name: 'Pera Glass',
        brand: 'Pro',
        image: 'imagenes/peraglass.png',
        description: 'Una nueva manera de ver.',
        price: 770,
        stock: 4,
    },
    {
        id: 9,
        name: 'Perahome',
        brand: 'Pera',
        image: 'imagenes/perahome.png',
        description: 'Pera también te da audio en casa.',
        price: 70,
        stock: 7,
    },
    {
        id: 10,
        name: 'Perapad Air',
        brand: 'Pera',
        image: 'imagenes/perapadair.png',
        description: 'El Perapad más liviano que hay.',
        price: 100,
        stock: 5,
    },
    {
        id: 11,
        name: 'Peraphone Pro',
        brand: 'Pro',
        image: 'imagenes/peraphonepro.jpg',
        description: 'El Peraphone recargado.',
        price: 499.99,
        stock: 2,
    },
];
